# ACCOUNT configuration stuff
account:
  openid:
    client:
      config: /tmp/trusted-denali-clients.json
      name: Resource Server (Denali)
      redirect-uri: http://localhost:1010/dummy-not-used
    context: http://localhost:8080/auth
    issuer: ${account.openid.context}/realms/${account.openid.keycloak.realm}
    keycloak:
      client-id: admin-cli
      password: ztar-keycloak
      master-realm: master
      realm: denali
      username: denali-keycloak

# HOST SERVER (where the service is running on)
server:
  address: denali.ztarmobile.com

spring:
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: xxxxxx
    test-while-idle: true
    url: jdbc:mysql://10.0.0.123:3306/cdrs?allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: ztar_db_user
    validation-query: SELECT 1
# Email (MailProperties)
  mail:
    defaultEncoding: UTF-8
    host: smtpout.secureserver.net
    password: unlmtd45
    port: 80
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
    username: admin@good2gomobile.com
# PROFILES
  profiles:
    active: "@activatedProperties@"
    