# BANNER
banner:
  charset: UTF-8
  location: classpath:com/ztarmobile/invoicing/config/banner.txt
  
# ENDPOINTS (AbstractEndpoint subclasses) curl -X POST localhost:${server.port}/shutdown
endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true
    sensitive: false

# MANAGEMENT HTTP SERVER (ManagementServerProperties)
management:
  security:
    enabled: false

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 38050

spring:
# IDENTITY (ContextIdApplicationContextInitializer)
  application:
    name: Invoicing Microservice v2
# PROJECT INFORMATION (ProjectInfoProperties)
  info:
    build:
      location: classpath:META-INF/build-info.properties  
# PROFILES
  profiles:
    active: @activatedProperties@
    
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/com/ztarmobile/invoicing/templates/
    suffix: .html