# BALANCE NOTIFICATION configuration stuff
notification:
  cron:
    activity: 0 0 7 1/1 * ? *
  ztarmobile: 
    context: https://10.0.0.11:9191/ztarmobile/webservices/rest/internal/zrm
    search:
      provider-uri: ${notification.ztarmobile.context}/account/search/provider
      ztar-uri: ${notification.ztarmobile.context}/account/search/ztar
    sender:
      sms-uri: ${notification.ztarmobile.context}/notification/sms

# LOGGING configuration stuff
logging:
  level:
    org:
      springframework:
        web: DEBUG

# HOST SERVER (where the service is running on)
server:
  address: localhost

spring:
# ACTIVEMQ (ActiveMQProperties)
  activemq:
    broker-url: tcp://10.0.0.122:61616
    in-memory: false
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource-cdrs:
    driver-class-name: com.mysql.jdbc.Driver
    password: xxxxxx
    test-while-idle: true
    url: jdbc:mysql://10.0.0.142:3306/cdrs?allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: xxxxxx
    validation-query: SELECT 1
  datasource-ztar:
    driver-class-name: com.mysql.jdbc.Driver
    password: xxxxxx
    test-while-idle: true
    url: jdbc:mysql://10.0.0.60:3306/ztar?allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: xxxxxx
    validation-query: SELECT 1
# Email (MailProperties)
  mail:
    defaultEncoding: UTF-8
    host: smtpout.secureserver.net
    password: unlmtd45
    port: 80
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
    username: admin@good2gomobile.com
# PROFILES
  profiles:
    active: "@activatedProperties@"
    